// This file contains seed data queries for development
// Run these manually using the SQL query tool in the Mocha dashboard

export const seedBrand = `
INSERT OR IGNORE INTO brands (id, name, slug, website_url, industry, status, verified_at)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'Omoda Jaecoo',
  'omoda-jaecoo',
  'https://omoda.com.uy',
  'automotive',
  'verified',
  datetime('now')
);
`;

export const seedAdmin = `
-- Note: You'll need to replace the password_hash with a real bcrypt hash
-- For password 'admin123' the hash would be generated by bcryptjs
INSERT OR IGNORE INTO users (id, email, password_hash, name, role, status)
VALUES (
  '00000000-0000-0000-0000-000000000002',
  'admin@omoda.local',
  '$2a$10$placeholder.hash.here',
  'Admin User',
  'superadmin',
  'active'
);
`;

export const seedBrandMember = `
INSERT OR IGNORE INTO brand_members (id, brand_id, user_id, role)
VALUES (
  '00000000-0000-0000-0000-000000000003',
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000002',
  'brand_admin'
);
`;

export const seedPosts = `
INSERT OR IGNORE INTO posts (id, brand_id, type, title, content, is_pinned, published)
VALUES 
(
  '00000000-0000-0000-0000-000000000004',
  '00000000-0000-0000-0000-000000000001',
  'announcement',
  'Welcome to Omoda Jaecoo',
  'We are excited to welcome you to the Omoda Jaecoo community. Activate your vehicle to unlock exclusive benefits and stay connected with the latest updates.',
  1,
  1
),
(
  '00000000-0000-0000-0000-000000000005',
  '00000000-0000-0000-0000-000000000001',
  'post',
  NULL,
  'New service packages now available! Get 15% off your next scheduled maintenance. Book through the app to redeem.',
  0,
  1
);
`;

export const seedEvents = `
INSERT OR IGNORE INTO events (id, brand_id, type, title, description, city, location_text, start_at, end_at, capacity, published)
VALUES 
(
  '00000000-0000-0000-0000-000000000006',
  '00000000-0000-0000-0000-000000000001',
  'service_clinic',
  'Service Clinic - Montevideo',
  'Complimentary vehicle inspection and maintenance consultation. Our expert technicians will review your vehicle and answer all your questions.',
  'Montevideo',
  'Casa Central - Av. Italia 2050',
  datetime('now', '+7 days'),
  datetime('now', '+7 days', '+3 hours'),
  50,
  1
),
(
  '00000000-0000-0000-0000-000000000007',
  '00000000-0000-0000-0000-000000000001',
  'event',
  'Test Drive Experience',
  'Experience the full Omoda lineup with our exclusive test drive event. Coffee and refreshments provided.',
  'Montevideo',
  'Kibón - Ruta 101',
  datetime('now', '+14 days'),
  datetime('now', '+14 days', '+5 hours'),
  80,
  1
);
`;

export const allSeeds = [
  seedBrand,
  seedAdmin,
  seedBrandMember,
  seedPosts,
  seedEvents,
].join('\n\n');
